name: Council Issue
description: Issue with an existing council
labels: ["bug"]

body:
    - type: input
      id: council
      attributes:
          label: Name of Council
          description: What council you were trying to use
          placeholder: e.g. Huntingdon District Council
      validations:
          required: true
    - type: textarea
      id: extra
      attributes:
        label: Issue Information
        description: What is the issue you're experiencing? How can we re-produce it?
        placeholder: Detailed explanation of the issue along with replication steps