services:
  devcontainer:
    image: ukbc_dev_container  # This tags the built image
    build:
      context: ../  # Path to the directory containing the Dockerfile
      dockerfile: .devcontainer/dev.Dockerfile
    volumes:
      - ../:/workspaces/UKBinCollectionData:rw
    privileged: true
    hostname: devcontainer
    networks:
      - devnet
    depends_on:
      - selenium-hub
    command: sleep infinity

  chrome:
    image: selenium/node-chrome:4.20.0-20240505
    shm_size: 2gb
    depends_on:
      - selenium-hub
    ports:
      - "7900:7900"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    privileged: true
    restart: always
    networks:
      - devnet

  chrome_video:
    image: selenium/video:ffmpeg-6.1.1-20240505
    volumes:
      - ../test_videos:/videos/
    depends_on:
      - chrome
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - SE_VIDEO_FILE_NAME=auto
      - SE_NODE_GRID_URL=http://selenium:4444
    privileged: true
    restart: always
    networks:
      - devnet

  selenium-hub:
    image: selenium/hub:4.20.0-20240505
    container_name: selenium-hub
    hostname: selenium
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    privileged: true
    restart: always
    networks:
      - devnet

networks:
  devnet:
    driver: bridge
