name: Test Councils

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
        poetry-version: [1.1.0]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run image
      uses: abatilo/actions-poetry@v2.1.5
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - name: setuptools < 58.0.0
      run: poetry run pip install 'setuptools==57.5.0'
    - name: Install
      run: make install
    - name: run integration tests
      run: make integration-tests
    - name: Upload Integration Test Coverage to Codecov
      uses: codecov/codecov-action@v3    
    - name: run unit tests
      run: make unit-tests
    - name: Upload Unit Test Coverage to Codecov
      uses: codecov/codecov-action@v3
    - name: Test Report
      uses: phoenix-actions/test-reporting@v8
      id: test-report               # Set ID reference for step
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: JEST Tests            # Name of the check run which will be created
        path: build/behave.reports/TESTS*.xml    # Path to test results
        reporter: jest-junit        # Format of test results     
