name: Build and publish package to PyPi

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run image
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: '1.5.1'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel twine

      - name: Install
        run: make install

      - name: Extract tag name
        id: tag
        run: echo ::set-output name=TAG_NAME::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Update pyproject.toml version
        run: |
          sed -i -E 's/version = \"([0-9.]+)\"/version = "${{ steps.tag.outputs.TAG_NAME }}"/g' pyproject.toml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update pyproject.toml version
          title: Update pyproject.toml version
          base: master
        continue-on-error: true

      - name: Build and publish package
        run: |
          poetry config pypi-token.pypi "${{ secrets.PYPI_API_KEY }}"
          poetry publish --build
